addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.5.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.4.4")
addSbtPlugin("com.github.sbt"            % "sbt-github-actions"   % "0.24.0")
addSbtPlugin("io.shiftleft"              % "sbt-ci-release-early" % "2.0.46")
addSbtPlugin("com.github.sbt"            % "sbt-dynver"           % "5.0.1")
